version: '3'
services:
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - ".:/my_mongo_app"
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  mongo-data:
